#!/bin/sh

DOTS=$(dirname "$0")/..
cd "$DOTS" || (echo "Directory not found: $DOTS"; exit 1)
DOTS="$PWD"

all_brews() {
    find "$DOTS/homebrew" \
        -iname "*.Brewfile" \
        -exec \
            /usr/local/bin/brew bundle install --file "{}" \;
    echo "all brews installed ✓"
}

all_brews
