#!/bin/sh

update_rust_analyzer() {
    if ! (which rust-analyzer > /dev/null)
    then
        echo "not installed"
    else
        echo "removing"
        rm /usr/local/bin/rust-analyzer
    fi
    echo "downloading rust analyzer"
    rust_analyzer_bin=/usr/local/bin/rust-analyzer
    curl -s -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-mac -o $rust_analyzer_bin
    chmod +x $rust_analyzer_bin

    echo "rust-analyzer ✓"
}

update_rust_analyzer
