tap "homebrew/cask"

# Shell Navigation
brew "exa"
brew "tmux"

# Shell Completion
brew "tldr"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"

# Searching
brew "the_silver_searcher"
brew "ripgrep"
brew "fzf"
brew "fd"

# File Manipulation
brew "sd"
brew "bat"
brew "jq"
brew "xsv"
brew "dos2unix"
brew "trash"

# Networking
brew "wget"
brew "telnet"
brew "prettyping"
brew "httpie"

# Languages
brew "shellcheck"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruby"
brew "ansible"
brew "terraform"
brew "packer"

# Miscellaneous
brew "gpg"
brew "emacs-plus"

# Fun
brew "qrencode"
brew "youtube-dl"
brew "googler"

# Personal
tap "nmasur/repo"
brew "nmasur/repo/drips"
brew "nmasur/repo/update-ssh-config"

# Not Installed
# git -- already installed
# hub -- github commands
# pulumi
# libmagic
# awscli
# saulpw/vd/visidata
# brew tap weaveworks/tap && brew install weaveworks/tap/eksctl (EKS on AWS)
# fasd (cd)
# glances (top)

