# Show these options
default:
  @just --list --list-heading $'Update NixOS config:\n'

channels:
  doas nix-channel --add https://nixos.org/channels/nixos-unstable
  doas nix-channel --add https://nixos.org/channels/nixpkgs-unstable
  doas nix-channel --update

# Update the system
system:
  doas nixos-rebuild switch -I nixos-config=./configuration.nix

# Update the user environment
home:
  home-manager switch -f ./home.nix
