#!/bin/sh

setup_keybase() {
    KEYBASE_USER=$(keybase whoami || (echo "Please login to keybase first"; exit 1))
    keybase fs sync enable "/keybase/private/$KEYBASE_USER"

    echo "keybase ✓"
}

backup_keybase_ssh() {
    SSH_DIR="/Volumes/Keybase/private/$KEYBASE_USER/ssh"
    if [ -d "$SSH_DIR" ]
    then
        rsync -a ~/.ssh/ "$SSH_DIR"/

        echo " - backed up to keybase: ssh ✓"
    else
        echo "Directory not found: $SSH_DIR"
        echo "Please check your keybase files"
        exit 1
    fi
}

backup_keybase_aws() {
    AWS_DIR="/Volumes/Keybase/private/$KEYBASE_USER/aws"
    if [ -d "$AWS_DIR" ]
    then
        rsync -a ~/.aws/ "$AWS_DIR"/

        echo " - backed up to keybase: aws ✓"
    else
        echo "Directory not found: $AWS_DIR"
        echo "Please check your keybase files"
        exit 1
    fi
}

setup_keybase
backup_keybase_ssh
backup_keybase_aws
