#!/bin/sh

DOTS=$(dirname "$0")/..
cd "$DOTS" || (echo "Directory not found: $DOTS"; exit 1)
DOTS="$PWD"

all_brews() {
    for brewfile in $(find "$DOTS/homebrew" -iname "*.Brewfile")
    do
        /usr/local/bin/brew bundle check --file "$brewfile" \
            && /usr/local/bin/brew bundle --file "$brewfile"
    done \
    && echo "all brews installed ✓"
}

all_brews
