#!/bin/sh

DOTS=$(dirname "$0")/..
cd "$DOTS" || (echo "Directory not found: $DOTS"; exit 1)
DOTS="$PWD"

setup_symlinks() {
    for source in $(find "$DOTS" -iname "*.symlink")
    do
        dest="$HOME/.`basename \"${source%.*}\"`"
        ln -sfn "$source" "$dest"
    done

    echo "symlinks ✓"
}

setup_configlinks() {
    for source in $(find "$DOTS" -iname "*.configlink")
    do
        dest="$HOME/.config/`basename \"${source%.*}\"`"
        ln -sfn "$source" "$dest"
    done

    echo "configlinks ✓"
}

setup_symlinks
setup_configlinks

