#!/usr/bin/env fish

# Install fisher packages
fisher update

# Set $PATH for finding programs
set -U FISH_DIR (readlink ~/.config/fish)
set -U DOTS (dirname $FISH_DIR)
set -U CDPATH . $HOME
set -U EDITOR nvim
set -U PROJ $HOME/dev/work
set -Ux NOTES_PATH $HOME/notes

# Load abbreviations
abbrs

# Turn off greeting
set -U fish_greeting ""

# Set colors (Base16 Eighties)
set -U fish_color_normal normal
set -U fish_color_command 99cc99
set -U fish_color_quote ffcc66
set -U fish_color_redirection d3d0c8
set -U fish_color_end cc99cc
set -U fish_color_error f2777a
set -U fish_color_selection white --bold --background=brblack
set -U fish_color_search_match bryellow --background=brblack
set -U fish_color_history_current --bold
set -U fish_color_operator 6699cc
set -U fish_color_escape 66cccc
set -U fish_color_cwd green
set -U fish_color_cwd_root red
set -U fish_color_valid_path --underline
set -U fish_color_autosuggestion 747369
set -U fish_color_user brgreen
set -U fish_color_host normal
set -U fish_color_cancel -r
set -U fish_pager_color_completion normal
set -U fish_pager_color_description B3A06D yellow
set -U fish_pager_color_prefix white --bold --underline
set -U fish_pager_color_progress brwhite --background=cyan
set -U fish_color_comment ffcc66
set -U fish_color_param d3d0c8
set -U fish_color_match 6699cc

echo "fish setup ✓"
